[[servers]]
  Address = "tcp://128.179.33.44:9002"
  Public = "YGVcHNL04jgooptanuI9HhliQvUIQmP8YFlGAWOg1uU="
  Description = "Conode_1"
[[servers]]
  Address = "tcp://128.179.33.44:9004"
  Public = "Hryth1Non0pzuDShGa4QLRne4F31aSyiVIiXzSEO9Hg="
  Description = "Conode_2"
[[servers]]
  Address = "tcp://128.179.33.44:9006"
  Public = "mAniPJvMXhJGkxXhF9WF1fnOMkx7zxPJkHFGNnbQQKk="
  Description = "Conode_3"
[[servers]]
  Address = "tcp://128.179.33.44:9008"
  Public = "EkCHS3VuSSdLZmdCmUfsXbjN8kIqbmrIqkScd1m9zAg="
  Description = "Conode_4"
[[servers]]
  Address = "tcp://128.179.33.44:9010"
  Public = "CvjsFqh+w443hI5MlmNEjwPvix87nZsx50VLVb+xqXc="
  Description = "Conode_5"
[[servers]]
  Address = "tcp://128.179.33.44:9012"
  Public = "yStJBCFfOlhkz6S4LPMOxZCK3FQeRDuUzOppfgokPrw="
  Description = "Conode_6"
[[servers]]
  Address = "tcp://128.179.33.44:9014"
  Public = "fOb2aAPV4mm1CbPx9vZZBpcMmtseYtNEaxJJa5ORlEI="
  Description = "Conode_7"
[[servers]]
  Address = "tcp://128.179.33.44:9016"
  Public = "hr0l9nVGbCPuUc1X0PPBN+2mWfKR1EBIaOOPQfO0ayI="
  Description = "Conode_8"
[[servers]]
  Address = "tcp://128.179.33.44:9018"
  Public = "eR8F1EuCEqQ85lwR1xyQIlE1wErDz+1nFwAWGmB0AU0="
  Description = "Conode_9"
[[servers]]
  Address = "tcp://128.179.33.44:9020"
  Public = "VN/hqLI0MuQgk2BwggG8lFW+3uqAzxqmX9vQfdjzVIw="
  Description = "Conode_10"
